### ISSUE TITLE
session.cookie.domain is not set for SAML IDP Cookie

### ISSUE THREAD

**Issue by GGeorggg** [center-for-learning-management/moodle-auth_samlidp#4]
moodle läuft auf http://test.eduvidual.at 
simplesamlidp auf http://idp.test.eduvidual.at

damit das Cookie mit dem SAML Request von http://test.eduvidual.at nach http://idp.test.eduvidual.at zurückgegeben werden kann, muss das Cookie mit der Cookie Domain .test.eduvidual.at zurückgegeben werden. 

Ich habe daher die setcookie Funktion in auth/samlidp/auth.php erweitert, bin mir nicht sicher ob dies so sein sollte, aber es funktioniert

**Comment by rschrenk** [comment]
warum hast du mich hier assigned?

**Comment by GGeorggg** [comment]
Hallo @rschrenk 

ich wollte wissen wie du das gelöst hast das der Cookie von einer Domaine in die andere übernommen wurde ohne dies im Plugin möglich ist ? Ich denke ich habe hier etwas falsch implementiert, wenn es auch funktioniert.

Defacto ist es aber ohnehin so, das die IDP Implementierung aktuell nicht (mehr) benötigt wird ?! 

https://github.com/center-for-learning-management/eduvidual-infrastructure/issues/1280#issuecomment-1268517966

**Comment by rschrenk** [comment]
Ich habe da nie bewusst etwas umkonfiguriert... könnte mich nicht daran erinnern.
